void dataOut();
void instructionsOut(char *s);
void declarationOut(char *s);
void assignOut(char *s);
void printOut(char *s);
void ifBoolOut();
void whileBoolOut();
void forBoolOut();
void ifOut(int a, int b);
void elseOut();
void endif();
void whileOut();
void forOut();
void substractOut();
void addOut();
void multOut();
void divOut();
int stackIndex(char *s);
void factorOutNum(int v);
void factorOutId(char *s, int v);
int indxVars(int v);
void negative();
