void dataOut();
void instructionsOut(char *s);
void declarationOut(char *s);
void assignOut(char *s, int v);
void printOut(char *s);
void ifOut();
void ifOut(int a, int b);
void elseOut();
void endif();
void whileOut();
void forOut();
void substractOut(float a, float b);
void addOut(float a, float b);
void multOut(float a, float b);
void divOut(float a, float b);
int stackIndex(char *s);
